/*
 * Decompiled with CFR 0.153-SNAPSHOT (d6f6758-dirty).
 */
package net.minecraft.client.model.geom;

import com.google.common.collect.ImmutableMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import net.minecraft.client.model.AbstractEquineModel;
import net.minecraft.client.model.AllayModel;
import net.minecraft.client.model.ArmadilloModel;
import net.minecraft.client.model.ArmorStandArmorModel;
import net.minecraft.client.model.ArmorStandModel;
import net.minecraft.client.model.ArrowModel;
import net.minecraft.client.model.AxolotlModel;
import net.minecraft.client.model.BannerFlagModel;
import net.minecraft.client.model.BannerModel;
import net.minecraft.client.model.BatModel;
import net.minecraft.client.model.BeeModel;
import net.minecraft.client.model.BeeStingerModel;
import net.minecraft.client.model.BellModel;
import net.minecraft.client.model.BlazeModel;
import net.minecraft.client.model.BoatModel;
import net.minecraft.client.model.BoggedModel;
import net.minecraft.client.model.BookModel;
import net.minecraft.client.model.BreezeModel;
import net.minecraft.client.model.CamelModel;
import net.minecraft.client.model.CamelSaddleModel;
import net.minecraft.client.model.CatModel;
import net.minecraft.client.model.ChestModel;
import net.minecraft.client.model.ChickenModel;
import net.minecraft.client.model.CodModel;
import net.minecraft.client.model.ColdChickenModel;
import net.minecraft.client.model.ColdCowModel;
import net.minecraft.client.model.ColdPigModel;
import net.minecraft.client.model.CowModel;
import net.minecraft.client.model.CreakingModel;
import net.minecraft.client.model.CreeperModel;
import net.minecraft.client.model.DolphinModel;
import net.minecraft.client.model.DonkeyModel;
import net.minecraft.client.model.DrownedModel;
import net.minecraft.client.model.ElytraModel;
import net.minecraft.client.model.EndCrystalModel;
import net.minecraft.client.model.EndermanModel;
import net.minecraft.client.model.EndermiteModel;
import net.minecraft.client.model.EquineSaddleModel;
import net.minecraft.client.model.EvokerFangsModel;
import net.minecraft.client.model.FelineModel;
import net.minecraft.client.model.FoxModel;
import net.minecraft.client.model.FrogModel;
import net.minecraft.client.model.GhastModel;
import net.minecraft.client.model.GoatModel;
import net.minecraft.client.model.GuardianModel;
import net.minecraft.client.model.HappyGhastHarnessModel;
import net.minecraft.client.model.HappyGhastModel;
import net.minecraft.client.model.HoglinModel;
import net.minecraft.client.model.HumanoidArmorModel;
import net.minecraft.client.model.HumanoidModel;
import net.minecraft.client.model.IllagerModel;
import net.minecraft.client.model.IronGolemModel;
import net.minecraft.client.model.LavaSlimeModel;
import net.minecraft.client.model.LeashKnotModel;
import net.minecraft.client.model.LlamaModel;
import net.minecraft.client.model.LlamaSpitModel;
import net.minecraft.client.model.MinecartModel;
import net.minecraft.client.model.PandaModel;
import net.minecraft.client.model.ParrotModel;
import net.minecraft.client.model.PhantomModel;
import net.minecraft.client.model.PigModel;
import net.minecraft.client.model.PiglinHeadModel;
import net.minecraft.client.model.PiglinModel;
import net.minecraft.client.model.PlayerCapeModel;
import net.minecraft.client.model.PlayerEarsModel;
import net.minecraft.client.model.PlayerModel;
import net.minecraft.client.model.PolarBearModel;
import net.minecraft.client.model.PufferfishBigModel;
import net.minecraft.client.model.PufferfishMidModel;
import net.minecraft.client.model.PufferfishSmallModel;
import net.minecraft.client.model.RabbitModel;
import net.minecraft.client.model.RaftModel;
import net.minecraft.client.model.RavagerModel;
import net.minecraft.client.model.SalmonModel;
import net.minecraft.client.model.SheepFurModel;
import net.minecraft.client.model.SheepModel;
import net.minecraft.client.model.ShieldModel;
import net.minecraft.client.model.ShulkerBulletModel;
import net.minecraft.client.model.ShulkerModel;
import net.minecraft.client.model.SilverfishModel;
import net.minecraft.client.model.SkeletonModel;
import net.minecraft.client.model.SkullModel;
import net.minecraft.client.model.SlimeModel;
import net.minecraft.client.model.SnifferModel;
import net.minecraft.client.model.SnowGolemModel;
import net.minecraft.client.model.SpiderModel;
import net.minecraft.client.model.SpinAttackEffectModel;
import net.minecraft.client.model.SquidModel;
import net.minecraft.client.model.StriderModel;
import net.minecraft.client.model.TadpoleModel;
import net.minecraft.client.model.TridentModel;
import net.minecraft.client.model.TropicalFishModelA;
import net.minecraft.client.model.TropicalFishModelB;
import net.minecraft.client.model.TurtleModel;
import net.minecraft.client.model.VexModel;
import net.minecraft.client.model.VillagerModel;
import net.minecraft.client.model.WardenModel;
import net.minecraft.client.model.WarmCowModel;
import net.minecraft.client.model.WindChargeModel;
import net.minecraft.client.model.WitchModel;
import net.minecraft.client.model.WitherBossModel;
import net.minecraft.client.model.WolfModel;
import net.minecraft.client.model.ZombieVillagerModel;
import net.minecraft.client.model.dragon.DragonHeadModel;
import net.minecraft.client.model.dragon.EnderDragonModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelLayers;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshTransformer;
import net.minecraft.client.renderer.blockentity.BedRenderer;
import net.minecraft.client.renderer.blockentity.ConduitRenderer;
import net.minecraft.client.renderer.blockentity.DecoratedPotRenderer;
import net.minecraft.client.renderer.blockentity.HangingSignRenderer;
import net.minecraft.client.renderer.blockentity.SignRenderer;
import net.minecraft.client.renderer.entity.WitherSkullRenderer;
import net.minecraft.world.level.block.state.properties.WoodType;

public class LayerDefinitions {
    private static final CubeDeformation FISH_PATTERN_DEFORMATION = new CubeDeformation(0.008f);
    private static final CubeDeformation OUTER_ARMOR_DEFORMATION = new CubeDeformation(1.0f);
    private static final CubeDeformation INNER_ARMOR_DEFORMATION = new CubeDeformation(0.5f);

    public static Map<ModelLayerLocation, LayerDefinition> createRoots() {
        ImmutableMap.Builder<ModelLayerLocation, LayerDefinition> $$0 = ImmutableMap.builder();
        LayerDefinition $$12 = LayerDefinition.create(HumanoidModel.createMesh(CubeDeformation.NONE, 0.0f), 64, 64);
        LayerDefinition $$2 = LayerDefinition.create(HumanoidArmorModel.createBodyLayer(OUTER_ARMOR_DEFORMATION), 64, 32);
        LayerDefinition $$32 = LayerDefinition.create(HumanoidArmorModel.createBodyLayer(new CubeDeformation(1.02f)), 64, 32);
        LayerDefinition $$4 = LayerDefinition.create(HumanoidArmorModel.createBodyLayer(INNER_ARMOR_DEFORMATION), 64, 32);
        LayerDefinition $$5 = MinecartModel.createBodyLayer();
        LayerDefinition $$6 = SkullModel.createMobHeadLayer();
        LayerDefinition $$7 = LayerDefinition.create(AbstractEquineModel.createBodyMesh(CubeDeformation.NONE), 64, 64);
        LayerDefinition $$8 = LayerDefinition.create(AbstractEquineModel.createBabyMesh(CubeDeformation.NONE), 64, 64);
        LayerDefinition $$9 = EquineSaddleModel.createSaddleLayer(false);
        LayerDefinition $$10 = EquineSaddleModel.createSaddleLayer(true);
        MeshTransformer $$11 = MeshTransformer.scaling(0.9375f);
        LayerDefinition $$122 = IllagerModel.createBodyLayer().apply($$11);
        LayerDefinition $$13 = AxolotlModel.createBodyLayer();
        LayerDefinition $$14 = BeeModel.createBodyLayer();
        LayerDefinition $$15 = CowModel.createBodyLayer();
        LayerDefinition $$16 = ColdChickenModel.createBodyLayer();
        LayerDefinition $$17 = ColdCowModel.createBodyLayer();
        LayerDefinition $$18 = ColdPigModel.createBodyLayer(CubeDeformation.NONE);
        LayerDefinition $$19 = ElytraModel.createLayer();
        LayerDefinition $$20 = LayerDefinition.create(FelineModel.createBodyMesh(CubeDeformation.NONE), 64, 32);
        LayerDefinition $$21 = $$20.apply(FelineModel.BABY_TRANSFORMER);
        LayerDefinition $$22 = LayerDefinition.create(FelineModel.createBodyMesh(new CubeDeformation(0.01f)), 64, 32);
        LayerDefinition $$23 = LayerDefinition.create(PiglinModel.createMesh(CubeDeformation.NONE), 64, 64);
        LayerDefinition $$24 = LayerDefinition.create(PiglinHeadModel.createHeadModel(), 64, 64);
        LayerDefinition $$25 = SkullModel.createHumanoidHeadLayer();
        LayerDefinition $$26 = LlamaModel.createBodyLayer(CubeDeformation.NONE);
        LayerDefinition $$27 = LlamaModel.createBodyLayer(new CubeDeformation(0.5f));
        LayerDefinition $$28 = StriderModel.createBodyLayer();
        LayerDefinition $$29 = HoglinModel.createBodyLayer();
        LayerDefinition $$30 = HoglinModel.createBabyLayer();
        LayerDefinition $$31 = SkeletonModel.createBodyLayer();
        LayerDefinition $$322 = LayerDefinition.create(VillagerModel.createBodyModel(), 64, 64).apply($$11);
        LayerDefinition $$33 = SpiderModel.createSpiderBodyLayer();
        LayerDefinition $$34 = ArmadilloModel.createBodyLayer();
        LayerDefinition $$35 = CamelModel.createBodyLayer();
        LayerDefinition $$36 = CamelSaddleModel.createSaddleLayer();
        LayerDefinition $$37 = ChickenModel.createBodyLayer();
        LayerDefinition $$38 = GoatModel.createBodyLayer();
        LayerDefinition $$39 = PandaModel.createBodyLayer();
        LayerDefinition $$40 = PigModel.createBodyLayer(CubeDeformation.NONE);
        LayerDefinition $$41 = PigModel.createBodyLayer(new CubeDeformation(0.5f));
        LayerDefinition $$42 = SheepModel.createBodyLayer();
        LayerDefinition $$43 = SheepFurModel.createFurLayer();
        LayerDefinition $$44 = SnifferModel.createBodyLayer();
        LayerDefinition $$45 = TurtleModel.createBodyLayer();
        LayerDefinition $$46 = WarmCowModel.createBodyLayer();
        LayerDefinition $$47 = LayerDefinition.create(WolfModel.createMeshDefinition(CubeDeformation.NONE), 64, 32);
        LayerDefinition $$48 = LayerDefinition.create(WolfModel.createMeshDefinition(new CubeDeformation(0.2f)), 64, 32);
        LayerDefinition $$49 = ZombieVillagerModel.createBodyLayer();
        LayerDefinition $$50 = ArmorStandModel.createBodyLayer();
        LayerDefinition $$51 = ArmorStandArmorModel.createBodyLayer(INNER_ARMOR_DEFORMATION);
        LayerDefinition $$52 = ArmorStandArmorModel.createBodyLayer(OUTER_ARMOR_DEFORMATION);
        LayerDefinition $$53 = DrownedModel.createBodyLayer(CubeDeformation.NONE);
        LayerDefinition $$54 = DrownedModel.createBodyLayer(new CubeDeformation(0.25f));
        LayerDefinition $$55 = SquidModel.createBodyLayer();
        LayerDefinition $$56 = DolphinModel.createBodyLayer();
        LayerDefinition $$57 = SalmonModel.createBodyLayer();
        $$0.put(ModelLayers.ALLAY, AllayModel.createBodyLayer());
        $$0.put(ModelLayers.ARMADILLO, $$34);
        $$0.put(ModelLayers.ARMADILLO_BABY, $$34.apply(ArmadilloModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.ARMOR_STAND, $$50);
        $$0.put(ModelLayers.ARMOR_STAND_INNER_ARMOR, $$51);
        $$0.put(ModelLayers.ARMOR_STAND_OUTER_ARMOR, $$52);
        $$0.put(ModelLayers.ARMOR_STAND_SMALL, $$50.apply(HumanoidModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.ARMOR_STAND_SMALL_INNER_ARMOR, $$51.apply(HumanoidModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.ARMOR_STAND_SMALL_OUTER_ARMOR, $$52.apply(HumanoidModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.ARROW, ArrowModel.createBodyLayer());
        $$0.put(ModelLayers.AXOLOTL, $$13);
        $$0.put(ModelLayers.AXOLOTL_BABY, $$13.apply(AxolotlModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.STANDING_BANNER, BannerModel.createBodyLayer(true));
        $$0.put(ModelLayers.WALL_BANNER, BannerModel.createBodyLayer(false));
        $$0.put(ModelLayers.STANDING_BANNER_FLAG, BannerFlagModel.createFlagLayer(true));
        $$0.put(ModelLayers.WALL_BANNER_FLAG, BannerFlagModel.createFlagLayer(false));
        $$0.put(ModelLayers.BAT, BatModel.createBodyLayer());
        $$0.put(ModelLayers.BED_FOOT, BedRenderer.createFootLayer());
        $$0.put(ModelLayers.BED_HEAD, BedRenderer.createHeadLayer());
        $$0.put(ModelLayers.BEE, $$14);
        $$0.put(ModelLayers.BEE_BABY, $$14.apply(BeeModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.BEE_STINGER, BeeStingerModel.createBodyLayer());
        $$0.put(ModelLayers.BELL, BellModel.createBodyLayer());
        $$0.put(ModelLayers.BLAZE, BlazeModel.createBodyLayer());
        $$0.put(ModelLayers.BOAT_WATER_PATCH, BoatModel.createWaterPatch());
        $$0.put(ModelLayers.BOGGED, BoggedModel.createBodyLayer());
        $$0.put(ModelLayers.BOGGED_INNER_ARMOR, $$4);
        $$0.put(ModelLayers.BOGGED_OUTER_ARMOR, $$2);
        $$0.put(ModelLayers.BOGGED_OUTER_LAYER, LayerDefinition.create(HumanoidModel.createMesh(new CubeDeformation(0.2f), 0.0f), 64, 32));
        $$0.put(ModelLayers.BOOK, BookModel.createBodyLayer());
        $$0.put(ModelLayers.BREEZE, BreezeModel.createBodyLayer(32, 32));
        $$0.put(ModelLayers.BREEZE_WIND, BreezeModel.createBodyLayer(128, 128));
        $$0.put(ModelLayers.CAT, $$20.apply(CatModel.CAT_TRANSFORMER));
        $$0.put(ModelLayers.CAT_BABY, $$21.apply(CatModel.CAT_TRANSFORMER));
        $$0.put(ModelLayers.CAT_COLLAR, $$22.apply(CatModel.CAT_TRANSFORMER));
        $$0.put(ModelLayers.CAT_BABY_COLLAR, $$22.apply(FelineModel.BABY_TRANSFORMER).apply(CatModel.CAT_TRANSFORMER));
        $$0.put(ModelLayers.CAMEL, $$35);
        $$0.put(ModelLayers.CAMEL_BABY, $$35.apply(CamelModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.CAMEL_SADDLE, $$36);
        $$0.put(ModelLayers.CAMEL_BABY_SADDLE, $$36.apply(CamelModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.CAVE_SPIDER, $$33.apply(MeshTransformer.scaling(0.7f)));
        $$0.put(ModelLayers.CHEST, ChestModel.createSingleBodyLayer());
        $$0.put(ModelLayers.CHEST_MINECART, $$5);
        $$0.put(ModelLayers.CHICKEN, $$37);
        $$0.put(ModelLayers.CHICKEN_BABY, $$37.apply(ChickenModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.COD, CodModel.createBodyLayer());
        $$0.put(ModelLayers.COLD_CHICKEN, $$16);
        $$0.put(ModelLayers.COLD_CHICKEN_BABY, $$16.apply(ChickenModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.COLD_COW, $$17);
        $$0.put(ModelLayers.COLD_COW_BABY, $$17.apply(CowModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.COLD_PIG, $$18);
        $$0.put(ModelLayers.COLD_PIG_BABY, $$18.apply(PigModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.COMMAND_BLOCK_MINECART, $$5);
        $$0.put(ModelLayers.CONDUIT_EYE, ConduitRenderer.createEyeLayer());
        $$0.put(ModelLayers.CONDUIT_WIND, ConduitRenderer.createWindLayer());
        $$0.put(ModelLayers.CONDUIT_SHELL, ConduitRenderer.createShellLayer());
        $$0.put(ModelLayers.CONDUIT_CAGE, ConduitRenderer.createCageLayer());
        $$0.put(ModelLayers.COW, $$15);
        $$0.put(ModelLayers.COW_BABY, $$15.apply(CowModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.CREAKING, CreakingModel.createBodyLayer());
        $$0.put(ModelLayers.CREEPER, CreeperModel.createBodyLayer(CubeDeformation.NONE));
        $$0.put(ModelLayers.CREEPER_ARMOR, CreeperModel.createBodyLayer(new CubeDeformation(2.0f)));
        $$0.put(ModelLayers.CREEPER_HEAD, $$6);
        $$0.put(ModelLayers.DECORATED_POT_BASE, DecoratedPotRenderer.createBaseLayer());
        $$0.put(ModelLayers.DECORATED_POT_SIDES, DecoratedPotRenderer.createSidesLayer());
        $$0.put(ModelLayers.DOLPHIN, $$56);
        $$0.put(ModelLayers.DOLPHIN_BABY, $$56.apply(DolphinModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.DONKEY, DonkeyModel.createBodyLayer(0.87f));
        $$0.put(ModelLayers.DONKEY_BABY, DonkeyModel.createBabyLayer(0.87f));
        $$0.put(ModelLayers.DONKEY_SADDLE, DonkeyModel.createSaddleLayer(0.87f, false));
        $$0.put(ModelLayers.DONKEY_BABY_SADDLE, DonkeyModel.createSaddleLayer(0.87f, true));
        $$0.put(ModelLayers.DOUBLE_CHEST_LEFT, ChestModel.createDoubleBodyLeftLayer());
        $$0.put(ModelLayers.DOUBLE_CHEST_RIGHT, ChestModel.createDoubleBodyRightLayer());
        $$0.put(ModelLayers.DRAGON_SKULL, DragonHeadModel.createHeadLayer());
        $$0.put(ModelLayers.DROWNED, $$53);
        $$0.put(ModelLayers.DROWNED_INNER_ARMOR, $$4);
        $$0.put(ModelLayers.DROWNED_OUTER_ARMOR, $$4);
        $$0.put(ModelLayers.DROWNED_OUTER_LAYER, $$54);
        $$0.put(ModelLayers.DROWNED_BABY, $$53.apply(HumanoidModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.DROWNED_BABY_INNER_ARMOR, $$4.apply(HumanoidModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.DROWNED_BABY_OUTER_ARMOR, $$4.apply(HumanoidModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.DROWNED_BABY_OUTER_LAYER, $$54.apply(HumanoidModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.ELDER_GUARDIAN, GuardianModel.createElderGuardianLayer());
        $$0.put(ModelLayers.ELYTRA, $$19);
        $$0.put(ModelLayers.ELYTRA_BABY, $$19.apply(ElytraModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.ENDERMAN, EndermanModel.createBodyLayer());
        $$0.put(ModelLayers.ENDERMITE, EndermiteModel.createBodyLayer());
        $$0.put(ModelLayers.ENDER_DRAGON, EnderDragonModel.createBodyLayer());
        $$0.put(ModelLayers.END_CRYSTAL, EndCrystalModel.createBodyLayer());
        $$0.put(ModelLayers.EVOKER, $$122);
        $$0.put(ModelLayers.EVOKER_FANGS, EvokerFangsModel.createBodyLayer());
        $$0.put(ModelLayers.FOX, FoxModel.createBodyLayer());
        $$0.put(ModelLayers.FOX_BABY, FoxModel.createBodyLayer().apply(FoxModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.FROG, FrogModel.createBodyLayer());
        $$0.put(ModelLayers.FURNACE_MINECART, $$5);
        $$0.put(ModelLayers.GHAST, GhastModel.createBodyLayer());
        MeshTransformer $$58 = MeshTransformer.scaling(6.0f);
        $$0.put(ModelLayers.GIANT, $$12.apply($$58));
        $$0.put(ModelLayers.GIANT_INNER_ARMOR, $$4.apply($$58));
        $$0.put(ModelLayers.GIANT_OUTER_ARMOR, $$2.apply($$58));
        $$0.put(ModelLayers.GLOW_SQUID, $$55);
        $$0.put(ModelLayers.GLOW_SQUID_BABY, $$55.apply(SquidModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.GOAT, $$38);
        $$0.put(ModelLayers.GOAT_BABY, $$38.apply(GoatModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.GUARDIAN, GuardianModel.createBodyLayer());
        $$0.put(ModelLayers.HAPPY_GHAST, HappyGhastModel.createBodyLayer(false, CubeDeformation.NONE));
        $$0.put(ModelLayers.HAPPY_GHAST_BABY, HappyGhastModel.createBodyLayer(true, CubeDeformation.NONE).apply(HappyGhastModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.HAPPY_GHAST_HARNESS, HappyGhastHarnessModel.createHarnessLayer(false));
        $$0.put(ModelLayers.HAPPY_GHAST_BABY_HARNESS, HappyGhastHarnessModel.createHarnessLayer(true).apply(HappyGhastModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.HAPPY_GHAST_ROPES, HappyGhastModel.createBodyLayer(false, new CubeDeformation(0.2f)));
        $$0.put(ModelLayers.HAPPY_GHAST_BABY_ROPES, HappyGhastModel.createBodyLayer(true, new CubeDeformation(0.2f)).apply(HappyGhastModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.HOGLIN, $$29);
        $$0.put(ModelLayers.HOGLIN_BABY, $$30);
        $$0.put(ModelLayers.HOPPER_MINECART, $$5);
        MeshTransformer $$59 = MeshTransformer.scaling(1.1f);
        $$0.put(ModelLayers.HORSE, $$7.apply($$59));
        $$0.put(ModelLayers.HORSE_BABY, $$8.apply($$59));
        $$0.put(ModelLayers.HORSE_ARMOR, LayerDefinition.create(AbstractEquineModel.createBodyMesh(new CubeDeformation(0.1f)), 64, 64).apply($$59));
        $$0.put(ModelLayers.HORSE_BABY_ARMOR, LayerDefinition.create(AbstractEquineModel.createBabyMesh(new CubeDeformation(0.1f)), 64, 64).apply($$59));
        $$0.put(ModelLayers.HORSE_SADDLE, $$9.apply($$59));
        $$0.put(ModelLayers.HORSE_BABY_SADDLE, $$10.apply($$59));
        MeshTransformer $$60 = MeshTransformer.scaling(1.0625f);
        $$0.put(ModelLayers.HUSK, $$12.apply($$60));
        $$0.put(ModelLayers.HUSK_INNER_ARMOR, $$4.apply($$60));
        $$0.put(ModelLayers.HUSK_OUTER_ARMOR, $$2.apply($$60));
        $$0.put(ModelLayers.HUSK_BABY, $$12.apply(HumanoidModel.BABY_TRANSFORMER).apply($$60));
        $$0.put(ModelLayers.HUSK_BABY_INNER_ARMOR, $$4.apply(HumanoidModel.BABY_TRANSFORMER).apply($$60));
        $$0.put(ModelLayers.HUSK_BABY_OUTER_ARMOR, $$2.apply(HumanoidModel.BABY_TRANSFORMER).apply($$60));
        $$0.put(ModelLayers.ILLUSIONER, $$122);
        $$0.put(ModelLayers.IRON_GOLEM, IronGolemModel.createBodyLayer());
        $$0.put(ModelLayers.LEASH_KNOT, LeashKnotModel.createBodyLayer());
        $$0.put(ModelLayers.LLAMA, $$26);
        $$0.put(ModelLayers.LLAMA_BABY, $$26.apply(LlamaModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.LLAMA_DECOR, $$27);
        $$0.put(ModelLayers.LLAMA_BABY_DECOR, $$27.apply(LlamaModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.LLAMA_SPIT, LlamaSpitModel.createBodyLayer());
        $$0.put(ModelLayers.MAGMA_CUBE, LavaSlimeModel.createBodyLayer());
        $$0.put(ModelLayers.MINECART, $$5);
        $$0.put(ModelLayers.MOOSHROOM, $$15);
        $$0.put(ModelLayers.MOOSHROOM_BABY, $$15.apply(CowModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.MULE, DonkeyModel.createBodyLayer(0.92f));
        $$0.put(ModelLayers.MULE_BABY, DonkeyModel.createBabyLayer(0.92f));
        $$0.put(ModelLayers.MULE_SADDLE, DonkeyModel.createSaddleLayer(0.92f, false));
        $$0.put(ModelLayers.MULE_BABY_SADDLE, DonkeyModel.createSaddleLayer(0.92f, true));
        $$0.put(ModelLayers.OCELOT, $$20);
        $$0.put(ModelLayers.OCELOT_BABY, $$21);
        $$0.put(ModelLayers.PANDA, $$39);
        $$0.put(ModelLayers.PANDA_BABY, $$39.apply(PandaModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.PARROT, ParrotModel.createBodyLayer());
        $$0.put(ModelLayers.PHANTOM, PhantomModel.createBodyLayer());
        $$0.put(ModelLayers.PIG, $$40);
        $$0.put(ModelLayers.PIG_BABY, $$40.apply(PigModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.PIG_SADDLE, $$41);
        $$0.put(ModelLayers.PIG_BABY_SADDLE, $$41.apply(PigModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.PIGLIN, $$23);
        $$0.put(ModelLayers.PIGLIN_INNER_ARMOR, $$4);
        $$0.put(ModelLayers.PIGLIN_OUTER_ARMOR, $$32);
        $$0.put(ModelLayers.PIGLIN_BRUTE, $$23);
        $$0.put(ModelLayers.PIGLIN_BRUTE_INNER_ARMOR, $$4);
        $$0.put(ModelLayers.PIGLIN_BRUTE_OUTER_ARMOR, $$32);
        $$0.put(ModelLayers.PIGLIN_BABY, $$23.apply(HumanoidModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.PIGLIN_BABY_INNER_ARMOR, $$4.apply(HumanoidModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.PIGLIN_BABY_OUTER_ARMOR, $$32.apply(HumanoidModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.PIGLIN_HEAD, $$24);
        $$0.put(ModelLayers.PILLAGER, $$122);
        $$0.put(ModelLayers.PLAYER, LayerDefinition.create(PlayerModel.createMesh(CubeDeformation.NONE, false), 64, 64));
        $$0.put(ModelLayers.PLAYER_EARS, PlayerEarsModel.createEarsLayer());
        $$0.put(ModelLayers.PLAYER_CAPE, PlayerCapeModel.createCapeLayer());
        $$0.put(ModelLayers.PLAYER_HEAD, $$25);
        $$0.put(ModelLayers.PLAYER_INNER_ARMOR, $$4);
        $$0.put(ModelLayers.PLAYER_OUTER_ARMOR, $$2);
        $$0.put(ModelLayers.PLAYER_SLIM, LayerDefinition.create(PlayerModel.createMesh(CubeDeformation.NONE, true), 64, 64));
        $$0.put(ModelLayers.PLAYER_SLIM_INNER_ARMOR, $$4);
        $$0.put(ModelLayers.PLAYER_SLIM_OUTER_ARMOR, $$2);
        $$0.put(ModelLayers.PLAYER_SPIN_ATTACK, SpinAttackEffectModel.createLayer());
        $$0.put(ModelLayers.POLAR_BEAR, PolarBearModel.createBodyLayer(false));
        $$0.put(ModelLayers.POLAR_BEAR_BABY, PolarBearModel.createBodyLayer(true));
        $$0.put(ModelLayers.PUFFERFISH_BIG, PufferfishBigModel.createBodyLayer());
        $$0.put(ModelLayers.PUFFERFISH_MEDIUM, PufferfishMidModel.createBodyLayer());
        $$0.put(ModelLayers.PUFFERFISH_SMALL, PufferfishSmallModel.createBodyLayer());
        $$0.put(ModelLayers.RABBIT, RabbitModel.createBodyLayer(false));
        $$0.put(ModelLayers.RABBIT_BABY, RabbitModel.createBodyLayer(true));
        $$0.put(ModelLayers.RAVAGER, RavagerModel.createBodyLayer());
        $$0.put(ModelLayers.SALMON, $$57);
        $$0.put(ModelLayers.SALMON_SMALL, $$57.apply(SalmonModel.SMALL_TRANSFORMER));
        $$0.put(ModelLayers.SALMON_LARGE, $$57.apply(SalmonModel.LARGE_TRANSFORMER));
        $$0.put(ModelLayers.SHEEP, $$42);
        $$0.put(ModelLayers.SHEEP_BABY, $$42.apply(SheepModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.SHEEP_WOOL, $$43);
        $$0.put(ModelLayers.SHEEP_BABY_WOOL, $$43.apply(SheepModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.SHEEP_WOOL_UNDERCOAT, $$42);
        $$0.put(ModelLayers.SHEEP_BABY_WOOL_UNDERCOAT, $$42.apply(SheepModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.SHIELD, ShieldModel.createLayer());
        $$0.put(ModelLayers.SHULKER, ShulkerModel.createBodyLayer());
        $$0.put(ModelLayers.SHULKER_BOX, ShulkerModel.createBoxLayer());
        $$0.put(ModelLayers.SHULKER_BULLET, ShulkerBulletModel.createBodyLayer());
        $$0.put(ModelLayers.SILVERFISH, SilverfishModel.createBodyLayer());
        $$0.put(ModelLayers.SKELETON, $$31);
        $$0.put(ModelLayers.SKELETON_INNER_ARMOR, $$4);
        $$0.put(ModelLayers.SKELETON_OUTER_ARMOR, $$2);
        $$0.put(ModelLayers.SKELETON_HORSE, $$7);
        $$0.put(ModelLayers.SKELETON_HORSE_BABY, $$8);
        $$0.put(ModelLayers.SKELETON_HORSE_SADDLE, $$9);
        $$0.put(ModelLayers.SKELETON_HORSE_BABY_SADDLE, $$10);
        $$0.put(ModelLayers.SKELETON_SKULL, $$6);
        $$0.put(ModelLayers.SLIME, SlimeModel.createInnerBodyLayer());
        $$0.put(ModelLayers.SLIME_OUTER, SlimeModel.createOuterBodyLayer());
        $$0.put(ModelLayers.SNIFFER, $$44);
        $$0.put(ModelLayers.SNIFFER_BABY, $$44.apply(SnifferModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.SNOW_GOLEM, SnowGolemModel.createBodyLayer());
        $$0.put(ModelLayers.SPAWNER_MINECART, $$5);
        $$0.put(ModelLayers.SPIDER, $$33);
        $$0.put(ModelLayers.SQUID, $$55);
        $$0.put(ModelLayers.SQUID_BABY, $$55.apply(SquidModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.STRAY, $$31);
        $$0.put(ModelLayers.STRAY_INNER_ARMOR, $$4);
        $$0.put(ModelLayers.STRAY_OUTER_ARMOR, $$2);
        $$0.put(ModelLayers.STRAY_OUTER_LAYER, LayerDefinition.create(HumanoidModel.createMesh(new CubeDeformation(0.25f), 0.0f), 64, 32));
        $$0.put(ModelLayers.STRIDER, $$28);
        $$0.put(ModelLayers.STRIDER_SADDLE, $$28);
        $$0.put(ModelLayers.STRIDER_BABY, $$28.apply(StriderModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.STRIDER_BABY_SADDLE, $$28.apply(StriderModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.TADPOLE, TadpoleModel.createBodyLayer());
        $$0.put(ModelLayers.TNT_MINECART, $$5);
        $$0.put(ModelLayers.TRADER_LLAMA, $$26);
        $$0.put(ModelLayers.TRADER_LLAMA_BABY, $$26.apply(LlamaModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.TRIDENT, TridentModel.createLayer());
        $$0.put(ModelLayers.TROPICAL_FISH_LARGE, TropicalFishModelB.createBodyLayer(CubeDeformation.NONE));
        $$0.put(ModelLayers.TROPICAL_FISH_LARGE_PATTERN, TropicalFishModelB.createBodyLayer(FISH_PATTERN_DEFORMATION));
        $$0.put(ModelLayers.TROPICAL_FISH_SMALL, TropicalFishModelA.createBodyLayer(CubeDeformation.NONE));
        $$0.put(ModelLayers.TROPICAL_FISH_SMALL_PATTERN, TropicalFishModelA.createBodyLayer(FISH_PATTERN_DEFORMATION));
        $$0.put(ModelLayers.TURTLE, $$45);
        $$0.put(ModelLayers.TURTLE_BABY, $$45.apply(TurtleModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.VEX, VexModel.createBodyLayer());
        $$0.put(ModelLayers.VILLAGER, $$322);
        $$0.put(ModelLayers.VILLAGER_BABY, $$322.apply(VillagerModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.VINDICATOR, $$122);
        $$0.put(ModelLayers.WARDEN, WardenModel.createBodyLayer());
        $$0.put(ModelLayers.WARM_COW, $$46);
        $$0.put(ModelLayers.WARM_COW_BABY, $$46.apply(CowModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.WANDERING_TRADER, $$322);
        $$0.put(ModelLayers.WIND_CHARGE, WindChargeModel.createBodyLayer());
        $$0.put(ModelLayers.WITCH, WitchModel.createBodyLayer().apply($$11));
        $$0.put(ModelLayers.WITHER, WitherBossModel.createBodyLayer(CubeDeformation.NONE));
        $$0.put(ModelLayers.WITHER_ARMOR, WitherBossModel.createBodyLayer(INNER_ARMOR_DEFORMATION));
        $$0.put(ModelLayers.WITHER_SKULL, WitherSkullRenderer.createSkullLayer());
        MeshTransformer $$61 = MeshTransformer.scaling(1.2f);
        $$0.put(ModelLayers.WITHER_SKELETON, $$31.apply($$61));
        $$0.put(ModelLayers.WITHER_SKELETON_INNER_ARMOR, $$4.apply($$61));
        $$0.put(ModelLayers.WITHER_SKELETON_OUTER_ARMOR, $$2.apply($$61));
        $$0.put(ModelLayers.WITHER_SKELETON_SKULL, $$6);
        $$0.put(ModelLayers.WOLF, $$47);
        $$0.put(ModelLayers.WOLF_ARMOR, $$48);
        $$0.put(ModelLayers.WOLF_BABY, $$47.apply(WolfModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.WOLF_BABY_ARMOR, $$48.apply(WolfModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.ZOGLIN, $$29);
        $$0.put(ModelLayers.ZOGLIN_BABY, $$30);
        $$0.put(ModelLayers.ZOMBIE, $$12);
        $$0.put(ModelLayers.ZOMBIE_INNER_ARMOR, $$4);
        $$0.put(ModelLayers.ZOMBIE_OUTER_ARMOR, $$2);
        $$0.put(ModelLayers.ZOMBIE_BABY, $$12.apply(HumanoidModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.ZOMBIE_BABY_INNER_ARMOR, $$4.apply(HumanoidModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.ZOMBIE_BABY_OUTER_ARMOR, $$2.apply(HumanoidModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.ZOMBIE_HEAD, $$25);
        $$0.put(ModelLayers.ZOMBIE_HORSE, $$7);
        $$0.put(ModelLayers.ZOMBIE_HORSE_BABY, $$8);
        $$0.put(ModelLayers.ZOMBIE_HORSE_SADDLE, $$9);
        $$0.put(ModelLayers.ZOMBIE_HORSE_BABY_SADDLE, $$10);
        $$0.put(ModelLayers.ZOMBIE_VILLAGER, $$49);
        $$0.put(ModelLayers.ZOMBIE_VILLAGER_INNER_ARMOR, ZombieVillagerModel.createArmorLayer(INNER_ARMOR_DEFORMATION));
        $$0.put(ModelLayers.ZOMBIE_VILLAGER_OUTER_ARMOR, ZombieVillagerModel.createArmorLayer(OUTER_ARMOR_DEFORMATION));
        $$0.put(ModelLayers.ZOMBIE_VILLAGER_BABY, $$49.apply(HumanoidModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.ZOMBIE_VILLAGER_BABY_INNER_ARMOR, ZombieVillagerModel.createArmorLayer(INNER_ARMOR_DEFORMATION).apply(HumanoidModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.ZOMBIE_VILLAGER_BABY_OUTER_ARMOR, ZombieVillagerModel.createArmorLayer(OUTER_ARMOR_DEFORMATION).apply(HumanoidModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.ZOMBIFIED_PIGLIN, $$23);
        $$0.put(ModelLayers.ZOMBIFIED_PIGLIN_INNER_ARMOR, $$4);
        $$0.put(ModelLayers.ZOMBIFIED_PIGLIN_OUTER_ARMOR, $$32);
        $$0.put(ModelLayers.ZOMBIFIED_PIGLIN_BABY, $$23.apply(HumanoidModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.ZOMBIFIED_PIGLIN_BABY_INNER_ARMOR, $$4.apply(HumanoidModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.ZOMBIFIED_PIGLIN_BABY_OUTER_ARMOR, $$32.apply(HumanoidModel.BABY_TRANSFORMER));
        $$0.put(ModelLayers.BAMBOO_RAFT, RaftModel.createRaftModel());
        $$0.put(ModelLayers.BAMBOO_CHEST_RAFT, RaftModel.createChestRaftModel());
        LayerDefinition $$62 = BoatModel.createBoatModel();
        LayerDefinition $$63 = BoatModel.createChestBoatModel();
        $$0.put(ModelLayers.OAK_BOAT, $$62);
        $$0.put(ModelLayers.OAK_CHEST_BOAT, $$63);
        $$0.put(ModelLayers.SPRUCE_BOAT, $$62);
        $$0.put(ModelLayers.SPRUCE_CHEST_BOAT, $$63);
        $$0.put(ModelLayers.BIRCH_BOAT, $$62);
        $$0.put(ModelLayers.BIRCH_CHEST_BOAT, $$63);
        $$0.put(ModelLayers.JUNGLE_BOAT, $$62);
        $$0.put(ModelLayers.JUNGLE_CHEST_BOAT, $$63);
        $$0.put(ModelLayers.ACACIA_BOAT, $$62);
        $$0.put(ModelLayers.ACACIA_CHEST_BOAT, $$63);
        $$0.put(ModelLayers.CHERRY_BOAT, $$62);
        $$0.put(ModelLayers.CHERRY_CHEST_BOAT, $$63);
        $$0.put(ModelLayers.DARK_OAK_BOAT, $$62);
        $$0.put(ModelLayers.DARK_OAK_CHEST_BOAT, $$63);
        $$0.put(ModelLayers.PALE_OAK_BOAT, $$62);
        $$0.put(ModelLayers.PALE_OAK_CHEST_BOAT, $$63);
        $$0.put(ModelLayers.MANGROVE_BOAT, $$62);
        $$0.put(ModelLayers.MANGROVE_CHEST_BOAT, $$63);
        LayerDefinition $$64 = SignRenderer.createSignLayer(true);
        LayerDefinition $$65 = SignRenderer.createSignLayer(false);
        WoodType.values().forEach($$3 -> {
            $$0.put(ModelLayers.createStandingSignModelName($$3), $$64);
            $$0.put(ModelLayers.createWallSignModelName($$3), $$65);
            for (HangingSignRenderer.AttachmentType $$4 : HangingSignRenderer.AttachmentType.values()) {
                LayerDefinition $$5 = HangingSignRenderer.createHangingSignLayer($$4);
                $$0.put(ModelLayers.createHangingSignModelName($$3, $$4), $$5);
            }
        });
        ImmutableMap<ModelLayerLocation, LayerDefinition> $$66 = $$0.build();
        List $$67 = ModelLayers.getKnownLocations().filter($$1 -> !$$66.containsKey($$1)).collect(Collectors.toList());
        if (!$$67.isEmpty()) {
            throw new IllegalStateException("Missing layer definitions: " + String.valueOf($$67));
        }
        return $$66;
    }
}

