/*
 * Decompiled with CFR 0.153-SNAPSHOT (d6f6758-dirty).
 */
package net.minecraft.tags;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;

public final class ItemTags {
    public static final TagKey<Item> WOOL = ItemTags.bind("wool");
    public static final TagKey<Item> PLANKS = ItemTags.bind("planks");
    public static final TagKey<Item> STONE_BRICKS = ItemTags.bind("stone_bricks");
    public static final TagKey<Item> WOODEN_BUTTONS = ItemTags.bind("wooden_buttons");
    public static final TagKey<Item> STONE_BUTTONS = ItemTags.bind("stone_buttons");
    public static final TagKey<Item> BUTTONS = ItemTags.bind("buttons");
    public static final TagKey<Item> WOOL_CARPETS = ItemTags.bind("wool_carpets");
    public static final TagKey<Item> WOODEN_DOORS = ItemTags.bind("wooden_doors");
    public static final TagKey<Item> WOODEN_STAIRS = ItemTags.bind("wooden_stairs");
    public static final TagKey<Item> WOODEN_SLABS = ItemTags.bind("wooden_slabs");
    public static final TagKey<Item> WOODEN_FENCES = ItemTags.bind("wooden_fences");
    public static final TagKey<Item> FENCE_GATES = ItemTags.bind("fence_gates");
    public static final TagKey<Item> WOODEN_PRESSURE_PLATES = ItemTags.bind("wooden_pressure_plates");
    public static final TagKey<Item> DOORS = ItemTags.bind("doors");
    public static final TagKey<Item> SAPLINGS = ItemTags.bind("saplings");
    public static final TagKey<Item> BAMBOO_BLOCKS = ItemTags.bind("bamboo_blocks");
    public static final TagKey<Item> OAK_LOGS = ItemTags.bind("oak_logs");
    public static final TagKey<Item> DARK_OAK_LOGS = ItemTags.bind("dark_oak_logs");
    public static final TagKey<Item> PALE_OAK_LOGS = ItemTags.bind("pale_oak_logs");
    public static final TagKey<Item> BIRCH_LOGS = ItemTags.bind("birch_logs");
    public static final TagKey<Item> ACACIA_LOGS = ItemTags.bind("acacia_logs");
    public static final TagKey<Item> SPRUCE_LOGS = ItemTags.bind("spruce_logs");
    public static final TagKey<Item> MANGROVE_LOGS = ItemTags.bind("mangrove_logs");
    public static final TagKey<Item> JUNGLE_LOGS = ItemTags.bind("jungle_logs");
    public static final TagKey<Item> CHERRY_LOGS = ItemTags.bind("cherry_logs");
    public static final TagKey<Item> CRIMSON_STEMS = ItemTags.bind("crimson_stems");
    public static final TagKey<Item> WARPED_STEMS = ItemTags.bind("warped_stems");
    public static final TagKey<Item> WART_BLOCKS = ItemTags.bind("wart_blocks");
    public static final TagKey<Item> LOGS_THAT_BURN = ItemTags.bind("logs_that_burn");
    public static final TagKey<Item> LOGS = ItemTags.bind("logs");
    public static final TagKey<Item> SAND = ItemTags.bind("sand");
    public static final TagKey<Item> SMELTS_TO_GLASS = ItemTags.bind("smelts_to_glass");
    public static final TagKey<Item> SLABS = ItemTags.bind("slabs");
    public static final TagKey<Item> WALLS = ItemTags.bind("walls");
    public static final TagKey<Item> STAIRS = ItemTags.bind("stairs");
    public static final TagKey<Item> ANVIL = ItemTags.bind("anvil");
    public static final TagKey<Item> RAILS = ItemTags.bind("rails");
    public static final TagKey<Item> LEAVES = ItemTags.bind("leaves");
    public static final TagKey<Item> WOODEN_TRAPDOORS = ItemTags.bind("wooden_trapdoors");
    public static final TagKey<Item> TRAPDOORS = ItemTags.bind("trapdoors");
    public static final TagKey<Item> SMALL_FLOWERS = ItemTags.bind("small_flowers");
    public static final TagKey<Item> FLOWERS = ItemTags.bind("flowers");
    public static final TagKey<Item> BEDS = ItemTags.bind("beds");
    public static final TagKey<Item> FENCES = ItemTags.bind("fences");
    public static final TagKey<Item> SOUL_FIRE_BASE_BLOCKS = ItemTags.bind("soul_fire_base_blocks");
    public static final TagKey<Item> CANDLES = ItemTags.bind("candles");
    public static final TagKey<Item> DAMPENS_VIBRATIONS = ItemTags.bind("dampens_vibrations");
    public static final TagKey<Item> GOLD_ORES = ItemTags.bind("gold_ores");
    public static final TagKey<Item> IRON_ORES = ItemTags.bind("iron_ores");
    public static final TagKey<Item> DIAMOND_ORES = ItemTags.bind("diamond_ores");
    public static final TagKey<Item> REDSTONE_ORES = ItemTags.bind("redstone_ores");
    public static final TagKey<Item> LAPIS_ORES = ItemTags.bind("lapis_ores");
    public static final TagKey<Item> COAL_ORES = ItemTags.bind("coal_ores");
    public static final TagKey<Item> EMERALD_ORES = ItemTags.bind("emerald_ores");
    public static final TagKey<Item> COPPER_ORES = ItemTags.bind("copper_ores");
    public static final TagKey<Item> DIRT = ItemTags.bind("dirt");
    public static final TagKey<Item> TERRACOTTA = ItemTags.bind("terracotta");
    public static final TagKey<Item> COMPLETES_FIND_TREE_TUTORIAL = ItemTags.bind("completes_find_tree_tutorial");
    public static final TagKey<Item> SHULKER_BOXES = ItemTags.bind("shulker_boxes");
    public static final TagKey<Item> SIGNS = ItemTags.bind("signs");
    public static final TagKey<Item> HANGING_SIGNS = ItemTags.bind("hanging_signs");
    public static final TagKey<Item> BEE_FOOD = ItemTags.bind("bee_food");
    public static final TagKey<Item> BANNERS = ItemTags.bind("banners");
    public static final TagKey<Item> PIGLIN_REPELLENTS = ItemTags.bind("piglin_repellents");
    public static final TagKey<Item> PIGLIN_LOVED = ItemTags.bind("piglin_loved");
    public static final TagKey<Item> IGNORED_BY_PIGLIN_BABIES = ItemTags.bind("ignored_by_piglin_babies");
    public static final TagKey<Item> PIGLIN_SAFE_ARMOR = ItemTags.bind("piglin_safe_armor");
    public static final TagKey<Item> DUPLICATES_ALLAYS = ItemTags.bind("duplicates_allays");
    public static final TagKey<Item> BREWING_FUEL = ItemTags.bind("brewing_fuel");
    public static final TagKey<Item> EGGS = ItemTags.bind("eggs");
    public static final TagKey<Item> MEAT = ItemTags.bind("meat");
    public static final TagKey<Item> SNIFFER_FOOD = ItemTags.bind("sniffer_food");
    public static final TagKey<Item> PIGLIN_FOOD = ItemTags.bind("piglin_food");
    public static final TagKey<Item> FOX_FOOD = ItemTags.bind("fox_food");
    public static final TagKey<Item> COW_FOOD = ItemTags.bind("cow_food");
    public static final TagKey<Item> GOAT_FOOD = ItemTags.bind("goat_food");
    public static final TagKey<Item> SHEEP_FOOD = ItemTags.bind("sheep_food");
    public static final TagKey<Item> WOLF_FOOD = ItemTags.bind("wolf_food");
    public static final TagKey<Item> CAT_FOOD = ItemTags.bind("cat_food");
    public static final TagKey<Item> HORSE_FOOD = ItemTags.bind("horse_food");
    public static final TagKey<Item> HORSE_TEMPT_ITEMS = ItemTags.bind("horse_tempt_items");
    public static final TagKey<Item> HARNESSES = ItemTags.bind("harnesses");
    public static final TagKey<Item> HAPPY_GHAST_FOOD = ItemTags.bind("happy_ghast_food");
    public static final TagKey<Item> HAPPY_GHAST_TEMPT_ITEMS = ItemTags.bind("happy_ghast_tempt_items");
    public static final TagKey<Item> CAMEL_FOOD = ItemTags.bind("camel_food");
    public static final TagKey<Item> ARMADILLO_FOOD = ItemTags.bind("armadillo_food");
    public static final TagKey<Item> CHICKEN_FOOD = ItemTags.bind("chicken_food");
    public static final TagKey<Item> FROG_FOOD = ItemTags.bind("frog_food");
    public static final TagKey<Item> HOGLIN_FOOD = ItemTags.bind("hoglin_food");
    public static final TagKey<Item> LLAMA_FOOD = ItemTags.bind("llama_food");
    public static final TagKey<Item> LLAMA_TEMPT_ITEMS = ItemTags.bind("llama_tempt_items");
    public static final TagKey<Item> OCELOT_FOOD = ItemTags.bind("ocelot_food");
    public static final TagKey<Item> PANDA_FOOD = ItemTags.bind("panda_food");
    public static final TagKey<Item> PANDA_EATS_FROM_GROUND = ItemTags.bind("panda_eats_from_ground");
    public static final TagKey<Item> PIG_FOOD = ItemTags.bind("pig_food");
    public static final TagKey<Item> RABBIT_FOOD = ItemTags.bind("rabbit_food");
    public static final TagKey<Item> STRIDER_FOOD = ItemTags.bind("strider_food");
    public static final TagKey<Item> STRIDER_TEMPT_ITEMS = ItemTags.bind("strider_tempt_items");
    public static final TagKey<Item> TURTLE_FOOD = ItemTags.bind("turtle_food");
    public static final TagKey<Item> PARROT_FOOD = ItemTags.bind("parrot_food");
    public static final TagKey<Item> PARROT_POISONOUS_FOOD = ItemTags.bind("parrot_poisonous_food");
    public static final TagKey<Item> AXOLOTL_FOOD = ItemTags.bind("axolotl_food");
    public static final TagKey<Item> NON_FLAMMABLE_WOOD = ItemTags.bind("non_flammable_wood");
    public static final TagKey<Item> BOATS = ItemTags.bind("boats");
    public static final TagKey<Item> CHEST_BOATS = ItemTags.bind("chest_boats");
    public static final TagKey<Item> FISHES = ItemTags.bind("fishes");
    public static final TagKey<Item> CREEPER_DROP_MUSIC_DISCS = ItemTags.bind("creeper_drop_music_discs");
    public static final TagKey<Item> COALS = ItemTags.bind("coals");
    public static final TagKey<Item> ARROWS = ItemTags.bind("arrows");
    public static final TagKey<Item> LECTERN_BOOKS = ItemTags.bind("lectern_books");
    public static final TagKey<Item> BOOKSHELF_BOOKS = ItemTags.bind("bookshelf_books");
    public static final TagKey<Item> BEACON_PAYMENT_ITEMS = ItemTags.bind("beacon_payment_items");
    public static final TagKey<Item> WOODEN_TOOL_MATERIALS = ItemTags.bind("wooden_tool_materials");
    public static final TagKey<Item> STONE_TOOL_MATERIALS = ItemTags.bind("stone_tool_materials");
    public static final TagKey<Item> IRON_TOOL_MATERIALS = ItemTags.bind("iron_tool_materials");
    public static final TagKey<Item> GOLD_TOOL_MATERIALS = ItemTags.bind("gold_tool_materials");
    public static final TagKey<Item> DIAMOND_TOOL_MATERIALS = ItemTags.bind("diamond_tool_materials");
    public static final TagKey<Item> NETHERITE_TOOL_MATERIALS = ItemTags.bind("netherite_tool_materials");
    public static final TagKey<Item> REPAIRS_LEATHER_ARMOR = ItemTags.bind("repairs_leather_armor");
    public static final TagKey<Item> REPAIRS_CHAIN_ARMOR = ItemTags.bind("repairs_chain_armor");
    public static final TagKey<Item> REPAIRS_IRON_ARMOR = ItemTags.bind("repairs_iron_armor");
    public static final TagKey<Item> REPAIRS_GOLD_ARMOR = ItemTags.bind("repairs_gold_armor");
    public static final TagKey<Item> REPAIRS_DIAMOND_ARMOR = ItemTags.bind("repairs_diamond_armor");
    public static final TagKey<Item> REPAIRS_NETHERITE_ARMOR = ItemTags.bind("repairs_netherite_armor");
    public static final TagKey<Item> REPAIRS_TURTLE_HELMET = ItemTags.bind("repairs_turtle_helmet");
    public static final TagKey<Item> REPAIRS_WOLF_ARMOR = ItemTags.bind("repairs_wolf_armor");
    public static final TagKey<Item> STONE_CRAFTING_MATERIALS = ItemTags.bind("stone_crafting_materials");
    public static final TagKey<Item> FREEZE_IMMUNE_WEARABLES = ItemTags.bind("freeze_immune_wearables");
    public static final TagKey<Item> CLUSTER_MAX_HARVESTABLES = ItemTags.bind("cluster_max_harvestables");
    public static final TagKey<Item> COMPASSES = ItemTags.bind("compasses");
    public static final TagKey<Item> CREEPER_IGNITERS = ItemTags.bind("creeper_igniters");
    public static final TagKey<Item> NOTE_BLOCK_TOP_INSTRUMENTS = ItemTags.bind("noteblock_top_instruments");
    public static final TagKey<Item> FOOT_ARMOR = ItemTags.bind("foot_armor");
    public static final TagKey<Item> LEG_ARMOR = ItemTags.bind("leg_armor");
    public static final TagKey<Item> CHEST_ARMOR = ItemTags.bind("chest_armor");
    public static final TagKey<Item> HEAD_ARMOR = ItemTags.bind("head_armor");
    public static final TagKey<Item> SKULLS = ItemTags.bind("skulls");
    public static final TagKey<Item> TRIMMABLE_ARMOR = ItemTags.bind("trimmable_armor");
    public static final TagKey<Item> TRIM_MATERIALS = ItemTags.bind("trim_materials");
    public static final TagKey<Item> DECORATED_POT_SHERDS = ItemTags.bind("decorated_pot_sherds");
    public static final TagKey<Item> DECORATED_POT_INGREDIENTS = ItemTags.bind("decorated_pot_ingredients");
    public static final TagKey<Item> SWORDS = ItemTags.bind("swords");
    public static final TagKey<Item> AXES = ItemTags.bind("axes");
    public static final TagKey<Item> HOES = ItemTags.bind("hoes");
    public static final TagKey<Item> PICKAXES = ItemTags.bind("pickaxes");
    public static final TagKey<Item> SHOVELS = ItemTags.bind("shovels");
    public static final TagKey<Item> BREAKS_DECORATED_POTS = ItemTags.bind("breaks_decorated_pots");
    public static final TagKey<Item> VILLAGER_PLANTABLE_SEEDS = ItemTags.bind("villager_plantable_seeds");
    public static final TagKey<Item> VILLAGER_PICKS_UP = ItemTags.bind("villager_picks_up");
    public static final TagKey<Item> DYEABLE = ItemTags.bind("dyeable");
    public static final TagKey<Item> FURNACE_MINECART_FUEL = ItemTags.bind("furnace_minecart_fuel");
    public static final TagKey<Item> BUNDLES = ItemTags.bind("bundles");
    public static final TagKey<Item> BOOK_CLONING_TARGET = ItemTags.bind("book_cloning_target");
    public static final TagKey<Item> SKELETON_PREFERRED_WEAPONS = ItemTags.bind("skeleton_preferred_weapons");
    public static final TagKey<Item> DROWNED_PREFERRED_WEAPONS = ItemTags.bind("drowned_preferred_weapons");
    public static final TagKey<Item> PIGLIN_PREFERRED_WEAPONS = ItemTags.bind("piglin_preferred_weapons");
    public static final TagKey<Item> PILLAGER_PREFERRED_WEAPONS = ItemTags.bind("pillager_preferred_weapons");
    public static final TagKey<Item> WITHER_SKELETON_DISLIKED_WEAPONS = ItemTags.bind("wither_skeleton_disliked_weapons");
    public static final TagKey<Item> FOOT_ARMOR_ENCHANTABLE = ItemTags.bind("enchantable/foot_armor");
    public static final TagKey<Item> LEG_ARMOR_ENCHANTABLE = ItemTags.bind("enchantable/leg_armor");
    public static final TagKey<Item> CHEST_ARMOR_ENCHANTABLE = ItemTags.bind("enchantable/chest_armor");
    public static final TagKey<Item> HEAD_ARMOR_ENCHANTABLE = ItemTags.bind("enchantable/head_armor");
    public static final TagKey<Item> ARMOR_ENCHANTABLE = ItemTags.bind("enchantable/armor");
    public static final TagKey<Item> SWORD_ENCHANTABLE = ItemTags.bind("enchantable/sword");
    public static final TagKey<Item> FIRE_ASPECT_ENCHANTABLE = ItemTags.bind("enchantable/fire_aspect");
    public static final TagKey<Item> SHARP_WEAPON_ENCHANTABLE = ItemTags.bind("enchantable/sharp_weapon");
    public static final TagKey<Item> WEAPON_ENCHANTABLE = ItemTags.bind("enchantable/weapon");
    public static final TagKey<Item> MINING_ENCHANTABLE = ItemTags.bind("enchantable/mining");
    public static final TagKey<Item> MINING_LOOT_ENCHANTABLE = ItemTags.bind("enchantable/mining_loot");
    public static final TagKey<Item> FISHING_ENCHANTABLE = ItemTags.bind("enchantable/fishing");
    public static final TagKey<Item> TRIDENT_ENCHANTABLE = ItemTags.bind("enchantable/trident");
    public static final TagKey<Item> DURABILITY_ENCHANTABLE = ItemTags.bind("enchantable/durability");
    public static final TagKey<Item> BOW_ENCHANTABLE = ItemTags.bind("enchantable/bow");
    public static final TagKey<Item> EQUIPPABLE_ENCHANTABLE = ItemTags.bind("enchantable/equippable");
    public static final TagKey<Item> CROSSBOW_ENCHANTABLE = ItemTags.bind("enchantable/crossbow");
    public static final TagKey<Item> VANISHING_ENCHANTABLE = ItemTags.bind("enchantable/vanishing");
    public static final TagKey<Item> MACE_ENCHANTABLE = ItemTags.bind("enchantable/mace");
    public static final TagKey<Item> MAP_INVISIBILITY_EQUIPMENT = ItemTags.bind("map_invisibility_equipment");
    public static final TagKey<Item> GAZE_DISGUISE_EQUIPMENT = ItemTags.bind("gaze_disguise_equipment");

    private ItemTags() {
    }

    private static TagKey<Item> bind(String $$0) {
        return TagKey.create(Registries.ITEM, ResourceLocation.withDefaultNamespace($$0));
    }
}

